### ISSUE TITLE
EDAM Ontology Doesn't Appear Properly

### ISSUE THREAD

**Issue by phidias51** [myGrid/RightField#13]
1. Open the EDAM Ontology using the "Open Ontology from BioPortal" menu item.
2. Search for "UniProt" 
3. I'm expecting to see all UniProt related items but what I see is a tree with node labels that don't really make any sense. They should display the names of the nodes, not the IDs like ":data_1234".

When I search for the same items in BioPortal then I see the names of all of the nodes that include the term "UniProt".

**Comment by phidias51** [comment]
I should also point out that when I try to load the OBI I get the same result.

**Comment by stuzart** [comment]
This seems related to issue #11 which I've been looking into. It is caused by a change in the latest version (issue #9) to display the prefix, but this seems to cause it to incorrectly display the literal rather than the label. 
I'm currently looking at reverting this change. I don't think the prefix is that helpful, and we do now also show the full IRI as a tooltip to help resolve ambiguities.

**Comment by stuzart** [comment]
This has now been fixed, and new downloads are available at https://rightfield.org.uk/download.html
